template_path: templates/jenkin-jumpbox.json

parameters:
  EnvironmentName: !stack_output ossbackbone::EnvironmentName
  SubnetId: !stack_output ossbackbone::PublicSubnet1
  WhitelistIP: 0.0.0.0/0
  JumpboxSecurityGroup: !stack_output jenkin-security-groups::JumpboxSecurityGroup