template_path: templates/ossbackbone.json

parameters:
  ProductName: OSSTOOLSSETUP
  EnvironmentName: ops
  VpcCIDR: 10.0.0.0/16
  PublicSubnet1CIDR: 10.0.10.0/24
  PublicSubnet2CIDR: 10.0.20.0/24
  PrivateSubnet1CIDR: 10.0.11.0/24
  PrivateSubnet2CIDR: 10.0.21.0/24
